# Generated by Django 5.2.4 on 2026-01-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_participant_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
