# Generated by Django 5.2.4 on 2026-01-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
